import type { Metadata } from "next";
import { LegalHeader } from "@/components/LegalHeader";

export const metadata: Metadata = { title: "Privacy Policy" };

const UPDATED = "September 24, 2026";

export default function PrivacyPage() {
  return (
    <>
      <LegalHeader />
      <main className="mx-auto w-full max-w-3xl px-4 pb-24 sm:px-6">
        <h1 className="font-serif text-4xl text-zinc-50">Privacy Policy</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated {UPDATED}</p>

        <div className="prose-legal mt-10 space-y-8 text-[15px] leading-relaxed text-zinc-300">
          <p>
            Lumina (&quot;we&quot;, &quot;us&quot;) is a journaling app with an AI &quot;Active
            Listener&quot; that reflects on what you write. This page explains what we collect,
            why, and how it&apos;s handled. It is not a substitute for legal advice — if you need
            a policy vetted for your specific jurisdiction or business, have a lawyer review this
            before relying on it.
          </p>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">What we collect</h2>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li><strong className="text-zinc-100">Account data:</strong> your email address and password (handled by our authentication provider, Supabase — we never see or store your raw password).</li>
              <li><strong className="text-zinc-100">Journal entries:</strong> the text you write, the Active Listener&apos;s replies, and, on the Paid plan, the values, recurring patterns and milestones our AI extracts from your entries over time (the &quot;Identity Board&quot;).</li>
              <li><strong className="text-zinc-100">Preferences:</strong> the onboarding choices you make about what you&apos;re journaling for, how you process things, and what tone you want from Lumina.</li>
              <li><strong className="text-zinc-100">Billing data, if you subscribe:</strong> our payment processor, Lemon Squeezy, collects your payment details directly — we never receive or store your card number. We receive only your subscription status, renewal dates, and a customer/subscription ID from them.</li>
              <li><strong className="text-zinc-100">Basic technical data:</strong> standard server logs (IP address, timestamps) generated by normal web hosting, used only for security and abuse prevention.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">How we use it</h2>
            <p className="mt-3">
              Your journal entries are sent to Anthropic&apos;s Claude API to generate each
              reflection and, on the Paid plan, to extract patterns and values for your Identity
              Board. They are not used to train Anthropic&apos;s models. We use your account data
              to run the service (authentication, showing you your own entries) and your billing
              data to know which plan you&apos;re on. We do not sell your data, and we do not use
              your journal entries for advertising.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">Who we share it with</h2>
            <p className="mt-3">
              Only the service providers required to run Lumina: <strong className="text-zinc-100">Supabase</strong> (database
              and authentication), <strong className="text-zinc-100">Anthropic</strong> (generating reflections), and{" "}
              <strong className="text-zinc-100">Lemon Squeezy</strong> (billing, as the merchant of record for
              subscriptions — they handle payment and tax compliance on our behalf). We don&apos;t
              share your journal content with anyone else, and we don&apos;t sell personal data.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">Your choices</h2>
            <p className="mt-3">
              You can update your preferences at any time from the Preferences page. To export or
              permanently delete your account and everything tied to it (entries, patterns,
              billing links), email us at{" "}
              <a href="mailto:support@lumina.app" className="text-indigo-300 hover:text-indigo-200">
                support@lumina.app
              </a>{" "}
              — we&apos;ll confirm and complete the deletion promptly. If you&apos;re in the EU/UK
              or California, this includes the access, correction, deletion and portability
              rights you have under GDPR/UK GDPR or the CCPA.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">Security &amp; retention</h2>
            <p className="mt-3">
              Data is encrypted in transit and at rest by our infrastructure providers. Row-level
              security ensures only you (and, for the minimum necessary processing, the AI
              services above) can access your entries. We keep your data for as long as your
              account is active, and delete it on request or account closure.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">Cookies</h2>
            <p className="mt-3">
              We use one strictly-necessary cookie to keep you signed in. We don&apos;t use
              advertising or cross-site tracking cookies.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">Changes</h2>
            <p className="mt-3">
              If we materially change this policy, we&apos;ll update the date above and, for
              significant changes, notify you by email.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-zinc-100">Contact</h2>
            <p className="mt-3">
              Questions about this policy or your data:{" "}
              <a href="mailto:support@lumina.app" className="text-indigo-300 hover:text-indigo-200">
                support@lumina.app
              </a>
            </p>
          </section>
        </div>
      </main>
    </>
  );
}
